### ISSUE TITLE
Add NET6 and NET8 to JetBrains.FormatRipper

### ISSUE THREAD

**Issue by Jetski5822** [JetBrains/format-ripper#52]
Hey, Snyk is reporting issues with Formatter ripper;

BenchmarkDotNet.Diagnostics.dotTrace@0.14.0 › JetBrains.Profiler.SelfApi@2.5.9 › JetBrains.HabitatDetector@1.4.1 › JetBrains.FormatRipper@2.2.1 › NETStandard.Library@1.6.1 › System.Net.Http@4.3.0

The projects we have at NET6 and NET8, but because FormatRipper is compile against netstandard1.0, its falling back to an older version.

Could you add NET6 and NET8 to the compilation targets?

**Comment by ww898** [comment]
`netstandard2.0` was added and will be available in next release.
